
#配置端口
server:
  port: 8080

spring:
  datasource:
    name: hanamiCamera
    type: com.alibaba.druid.pool.DruidDataSource
    #基本属性
    url: jdbc:mysql://127.0.0.1:3306/hanami_camera?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages/
    suffix: .html
# Mybatis配置
mybatis:
  # 配置XML映射文件中指定的实体类别名路径
  type-aliases-package: hanamiCamera/entity
  # 配置MyBatis的xml配置文件路径
  mapper-locations: classpath:mapper/*.xml

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}
